# Server Port (8080)
server.port=8080

# Name of Application
spring.application.name=colourgen-project

# Format JSON
spring.jackson.serialization.indent-output=true

# H2-Database, in memory
spring.datasource.url=jdbc:postgresql://localhost:5432/colourgen
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=colourgen
spring.datasource.password=${DB_PASSWORD}

#H2-Console. Browser access via: http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=aplpha

#In production:
#springdoc.api-docs.enable=false
#springdoc.swagger-ui.enabled=false

color.api.base-url=https://www.thecolorapi.com
color.api.key=${COLOUR_API_KEY:DEMO_KEY}
color.api.connect-timeout-ms=2000
color.api.read-timeout-ms=5000


